# this is workflow name
name: hello

#run on tigger
on:
  workflow_dispatch: 
# these are jobs inside workflow
jobs:
  # this is the name of jobs
  greet:
    #this is github runner, each jobs runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: says to hello users
        run: echo "Hello dosto"

      - name: says hello to Username
        run: echo "Hello $USER"
   # this is the name of jobs 2nd     
  details:
    #this is rnner,
    runs-on: ubuntu-latest
    steps:
      # find version of docker and python
      - name: show the version name of python & docker
        run: docker --version && python --version
  
      
    
  
